### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by ver24436** [jasonwynn10/PM-Beacons#7]
### Issue description

- Expected result: The plugin won't affect other aspects of the game, such as crafting.

- Actual result: When this plugin is used, players are unable to craft, any attempt reverts the items to their default state.

### Steps to reproduce the issue
1. Install a current version of PMMP 
2. Install the PM-Beacon Plugin
3. Run the server and attempt to craft anything while in survival mode.
4. Any item crafted will revert to its default state.

### OS and versions
* PocketMine-MP: PMMP 3.11.4 / v 1.14.0 (protocol version 389)
* PHP: 7.3.8
* Server OS: Microsoft Windows 10 Pro [Version 10.0.18362.10024]
* Game version: Win10 1.14.9.0

### Plugins
PM-Beacons v0.0.1

- If you remove all plugins, does the issue still occur?
No, if I remove the plugin, the problem does not occur.

I believe this is related to the same issue that impacted the Teaspoon plugin. 

https://github.com/CortexPE/TeaSpoon/pull/469/commits/0faa62dd25a693f19b6c01110f58e0d0a4b4aace

https://streamable.com/s/y0csm/kbpfpf

**Comment by jasonw4331** [comment]
This is invalid due to the crafting recipe not being implemented
