### ISSUE TITLE
Crafting is bugged after installing this plugin

### ISSUE THREAD

**Issue by Johnsonk79** [jasonwynn10/PM-Beacons#8]
After the plugin is installed, crafting anything in any game mode in the crafting bench or inventory will be bugged, and as soon as the crafted item is being held it changes back to the original material
(Example: Crafted 4 sticks with 2 planks, once the stick is held or clicked it changes back to 2 planks)

**This issue only occurs with this plugin installed, and no other plugins in the server.**

PocketMine-MP 3.11.4 for Minecraft: Bedrock Edition v1.14.0 (protocol version 389)

**Comment by ver24436** [comment]
The same issue I reported and was closed invalid.
